import 'dart:io';

import 'package:flutter/material.dart';
import 'package:news_top_headlines/viewmodels/NewsArticleListViewModel.dart';
import 'package:news_top_headlines/views/NewsListView.dart';
import 'package:provider/provider.dart';
import 'helpers/CustomHttpOverrides.dart';

// void main() => runApp(MyApp());

void main() async {
  //  Trust the SSL certificates generated by Charles SSL Proxying.
  HttpOverrides.global = CustomHttpOverrides();

  // Run app
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'News App',
        //   home: ChangeNotifierProvider(˜
        //   builder: (_) => NewsArticleListViewModel(),
        //   create: (BuildContext context) {  },
        //   child: NewsListView()
        // )

        home: ChangeNotifierProvider(
          create: (_) => new NewsArticleListViewModel(),
          child: NewsListView(),
        )

        // Scaffold(
        //   appBar: AppBar(
        //     title: Text("Latest news")
        //   ),
        //   body: Text("Latest body"),
        // )
        );
  }
}
