import 'package:flutter/foundation.dart';
import 'custom_proxy.dart';

/// The ProxyManager which allows to Configuration [Charles SSL Proxy] for your app.
/// It trust the [SSL certificates] generated by [Charles SSL Proxy].

void proxyConfiguration() {
  if (!kReleaseMode) {
    /// For Android devices you can also allowBadCertificates: true below, but you should ONLY do this when !kReleaseMode
    /// Restart emulator or simulator to fix certificate issue
    final proxy = CustomProxy(ipAddress: "localhost", port: 8888);

    /// Set [isProxyEnabled] in [CustomProxy] to true if you want to enable proxy and vice-versa
    proxy.isProxyEnabled ? proxy.enable() : proxy.disable();
  }
}
